apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: dev-

replicas:
  - name: kafka-load-tester
    count: 1

configMapGenerator:
  - name: kafka-load-tester-config
    behavior: merge
    literals:
      - kafka_bootstrap_servers=kafka-kafka-bootstrap.kafka.svc:9092
      - producer_pool_size=3

patchesStrategicMerge:
  - resources.yaml