apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: prod-

replicas:
  - name: kafka-load-tester
    count: 2

configMapGenerator:
  - name: kafka-load-tester-config
    behavior: merge
    literals:
      - kafka_bootstrap_servers=kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
      - producer_pool_size=5

patchesStrategicMerge:
  - resources.yaml
  - service.yaml