apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-load-tester-config
  labels:
    app: kafka-load-tester
data:
  kafka_bootstrap_servers: "kafka-kafka-bootstrap:9092"
  kafka_topic: "load-test"
  kafka_compression_type: "snappy"
  kafka_acks: "1"
  producer_pool_size: "5"